sonar.projectKey=fieldops-mobile-technician
sonar.projectName=FieldOps Mobile Technician
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=node_modules/**,www/**,android/**,ios/**,**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
